=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module NutanixVmm
  # A collection of VM stats.
  class VmmV40EsxiStatsVmStatsTuple < ApiModelBase
    # The VM NCC health check score.
    attr_accessor :check_score

    # The UUID of the cluster on which the VM resides.
    attr_accessor :cluster

    # The VM controller average I/O latency in microseconds.
    attr_accessor :controller_avg_io_latency_micros

    # The VM controller average read I/O latency in microseconds.
    attr_accessor :controller_avg_read_io_latency_micros

    # The VM controller average read I/O size in kilobytes.
    attr_accessor :controller_avg_read_io_size_kb

    # The VM controller average write I/O latency in microseconds.
    attr_accessor :controller_avg_write_io_latency_micros

    # The VM controller average write I/O size in kilobytes.
    attr_accessor :controller_avg_write_io_size_kb

    # The VM controller I/O bandwidth in kilobytes per second.
    attr_accessor :controller_io_bandwidth_kbps

    # The VM controller number of I/O requests.
    attr_accessor :controller_num_io

    # The VM controller number of I/O operations per second.
    attr_accessor :controller_num_iops

    # The VM controller number of random I/O.
    attr_accessor :controller_num_random_io

    # The VM controller number of read I/O.
    attr_accessor :controller_num_read_io

    # The VM controller number of read I/O operations per second.
    attr_accessor :controller_num_read_iops

    # The VM controller number of sequential I/Os.
    attr_accessor :controller_num_seq_io

    # The VM controller number of write I/O.
    attr_accessor :controller_num_write_io

    # The VM controller number of write I/O operations per second.
    attr_accessor :controller_num_write_iops

    # The VM controller number of random I/O PPM.
    attr_accessor :controller_random_io_ppm

    # The VM controller number of read I/O bandwidth in kilobytes per second.
    attr_accessor :controller_read_io_bandwidth_kbps

    # The VM controller number of read I/O PPM.
    attr_accessor :controller_read_io_ppm

    # The VM controller number of sequential I/O PPM.
    attr_accessor :controller_seq_io_ppm

    # The VM controller total usage on SSD tier for the VM.
    attr_accessor :controller_storage_tier_ssd_usage_bytes

    # The VM controller timespan in microseconds.
    attr_accessor :controller_timespan_micros

    # The VM controller number of total I/O size in kilobytes.
    attr_accessor :controller_total_io_size_kb

    # The VM controller number of total I/O time in microseconds.
    attr_accessor :controller_total_io_time_micros

    # The VM controller number of total read I/O size in kilobytes.
    attr_accessor :controller_total_read_io_size_kb

    # The VM controller number of total read I/O time in microseconds.
    attr_accessor :controller_total_read_io_time_micros

    # The VM controller number of total transformed usage in bytes.
    attr_accessor :controller_total_transformed_usage_bytes

    # The VM controller user bytes.
    attr_accessor :controller_user_bytes

    # The VM controller write I/O bandwidth in kilobytes per second.
    attr_accessor :controller_write_io_bandwidth_kbps

    # The VM controller percentage of write I/O in parts per million.
    attr_accessor :controller_write_io_ppm

    # The average I/O latency of the VM in microseconds
    attr_accessor :hypervisor_avg_io_latency_micros

    # Percentage of time that the VM was ready, but could not get scheduled to run.
    attr_accessor :hypervisor_cpu_ready_time_ppm

    # The CPU usage of the VM in parts per million.
    attr_accessor :hypervisor_cpu_usage_ppm

    # The I/O bandwidth of the VM in kilobytes per second.
    attr_accessor :hypervisor_io_bandwidth_kbps

    # Consolidated guest memory usage in percentage.
    attr_accessor :hypervisor_memory_usage_ppm

    # The number of I/O by the VM.
    attr_accessor :hypervisor_num_io

    # The number of I/O operations by the VM per second.
    attr_accessor :hypervisor_num_iops

    # The number of read I/O operations by the VM.
    attr_accessor :hypervisor_num_read_io

    # The number of read I/O operations by the VM per second.
    attr_accessor :hypervisor_num_read_iops

    # The number of bytes received by the VM.
    attr_accessor :hypervisor_num_received_bytes

    # The number of bytes transmitted by the VM.
    attr_accessor :hypervisor_num_transmitted_bytes

    # The number of write I/O by the VM.
    attr_accessor :hypervisor_num_write_io

    # The number of write I/O operations by the VM per second.
    attr_accessor :hypervisor_num_write_iops

    # The number of read I/O bandwidth of the VM in kilobytes per second.
    attr_accessor :hypervisor_read_io_bandwidth_kbps

    # The swap in rate of the VM in kilobytes per second.
    attr_accessor :hypervisor_swap_in_rate_kbps

    # The swap out rate of the VM in kilobytes per second.
    attr_accessor :hypervisor_swap_out_rate_kbps

    # The timespan of the VM in microseconds.
    attr_accessor :hypervisor_timespan_micros

    # The total I/O size of the VM in kilobytes.
    attr_accessor :hypervisor_total_io_size_kb

    # The total I/O time of the VM in microseconds.
    attr_accessor :hypervisor_total_io_time_micros

    # The total read I/O size of the VM in kilobytes.
    attr_accessor :hypervisor_total_read_io_size_kb

    # The write I/O bandwidth of the VM in kilobytes per second.
    attr_accessor :hypervisor_write_io_bandwidth_kbps

    # Hypervisor type of the VM.
    attr_accessor :hypervisor_type

    # The VM memory usage in PPM.
    attr_accessor :memory_usage_ppm

    # The timestamp of a specific VM stats response data point.
    attr_accessor :timestamp

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'check_score' => :'checkScore',
        :'cluster' => :'cluster',
        :'controller_avg_io_latency_micros' => :'controllerAvgIoLatencyMicros',
        :'controller_avg_read_io_latency_micros' => :'controllerAvgReadIoLatencyMicros',
        :'controller_avg_read_io_size_kb' => :'controllerAvgReadIoSizeKb',
        :'controller_avg_write_io_latency_micros' => :'controllerAvgWriteIoLatencyMicros',
        :'controller_avg_write_io_size_kb' => :'controllerAvgWriteIoSizeKb',
        :'controller_io_bandwidth_kbps' => :'controllerIoBandwidthKbps',
        :'controller_num_io' => :'controllerNumIo',
        :'controller_num_iops' => :'controllerNumIops',
        :'controller_num_random_io' => :'controllerNumRandomIo',
        :'controller_num_read_io' => :'controllerNumReadIo',
        :'controller_num_read_iops' => :'controllerNumReadIops',
        :'controller_num_seq_io' => :'controllerNumSeqIo',
        :'controller_num_write_io' => :'controllerNumWriteIo',
        :'controller_num_write_iops' => :'controllerNumWriteIops',
        :'controller_random_io_ppm' => :'controllerRandomIoPpm',
        :'controller_read_io_bandwidth_kbps' => :'controllerReadIoBandwidthKbps',
        :'controller_read_io_ppm' => :'controllerReadIoPpm',
        :'controller_seq_io_ppm' => :'controllerSeqIoPpm',
        :'controller_storage_tier_ssd_usage_bytes' => :'controllerStorageTierSsdUsageBytes',
        :'controller_timespan_micros' => :'controllerTimespanMicros',
        :'controller_total_io_size_kb' => :'controllerTotalIoSizeKb',
        :'controller_total_io_time_micros' => :'controllerTotalIoTimeMicros',
        :'controller_total_read_io_size_kb' => :'controllerTotalReadIoSizeKb',
        :'controller_total_read_io_time_micros' => :'controllerTotalReadIoTimeMicros',
        :'controller_total_transformed_usage_bytes' => :'controllerTotalTransformedUsageBytes',
        :'controller_user_bytes' => :'controllerUserBytes',
        :'controller_write_io_bandwidth_kbps' => :'controllerWriteIoBandwidthKbps',
        :'controller_write_io_ppm' => :'controllerWriteIoPpm',
        :'hypervisor_avg_io_latency_micros' => :'hypervisorAvgIoLatencyMicros',
        :'hypervisor_cpu_ready_time_ppm' => :'hypervisorCpuReadyTimePpm',
        :'hypervisor_cpu_usage_ppm' => :'hypervisorCpuUsagePpm',
        :'hypervisor_io_bandwidth_kbps' => :'hypervisorIoBandwidthKbps',
        :'hypervisor_memory_usage_ppm' => :'hypervisorMemoryUsagePpm',
        :'hypervisor_num_io' => :'hypervisorNumIo',
        :'hypervisor_num_iops' => :'hypervisorNumIops',
        :'hypervisor_num_read_io' => :'hypervisorNumReadIo',
        :'hypervisor_num_read_iops' => :'hypervisorNumReadIops',
        :'hypervisor_num_received_bytes' => :'hypervisorNumReceivedBytes',
        :'hypervisor_num_transmitted_bytes' => :'hypervisorNumTransmittedBytes',
        :'hypervisor_num_write_io' => :'hypervisorNumWriteIo',
        :'hypervisor_num_write_iops' => :'hypervisorNumWriteIops',
        :'hypervisor_read_io_bandwidth_kbps' => :'hypervisorReadIoBandwidthKbps',
        :'hypervisor_swap_in_rate_kbps' => :'hypervisorSwapInRateKbps',
        :'hypervisor_swap_out_rate_kbps' => :'hypervisorSwapOutRateKbps',
        :'hypervisor_timespan_micros' => :'hypervisorTimespanMicros',
        :'hypervisor_total_io_size_kb' => :'hypervisorTotalIoSizeKb',
        :'hypervisor_total_io_time_micros' => :'hypervisorTotalIoTimeMicros',
        :'hypervisor_total_read_io_size_kb' => :'hypervisorTotalReadIoSizeKb',
        :'hypervisor_write_io_bandwidth_kbps' => :'hypervisorWriteIoBandwidthKbps',
        :'hypervisor_type' => :'hypervisorType',
        :'memory_usage_ppm' => :'memoryUsagePpm',
        :'timestamp' => :'timestamp'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'check_score' => :'Integer',
        :'cluster' => :'String',
        :'controller_avg_io_latency_micros' => :'Integer',
        :'controller_avg_read_io_latency_micros' => :'Integer',
        :'controller_avg_read_io_size_kb' => :'Integer',
        :'controller_avg_write_io_latency_micros' => :'Integer',
        :'controller_avg_write_io_size_kb' => :'Integer',
        :'controller_io_bandwidth_kbps' => :'Integer',
        :'controller_num_io' => :'Integer',
        :'controller_num_iops' => :'Integer',
        :'controller_num_random_io' => :'Integer',
        :'controller_num_read_io' => :'Integer',
        :'controller_num_read_iops' => :'Integer',
        :'controller_num_seq_io' => :'Integer',
        :'controller_num_write_io' => :'Integer',
        :'controller_num_write_iops' => :'Integer',
        :'controller_random_io_ppm' => :'Integer',
        :'controller_read_io_bandwidth_kbps' => :'Integer',
        :'controller_read_io_ppm' => :'Integer',
        :'controller_seq_io_ppm' => :'Integer',
        :'controller_storage_tier_ssd_usage_bytes' => :'Integer',
        :'controller_timespan_micros' => :'Integer',
        :'controller_total_io_size_kb' => :'Integer',
        :'controller_total_io_time_micros' => :'Integer',
        :'controller_total_read_io_size_kb' => :'Integer',
        :'controller_total_read_io_time_micros' => :'Integer',
        :'controller_total_transformed_usage_bytes' => :'Integer',
        :'controller_user_bytes' => :'Integer',
        :'controller_write_io_bandwidth_kbps' => :'Integer',
        :'controller_write_io_ppm' => :'Integer',
        :'hypervisor_avg_io_latency_micros' => :'Integer',
        :'hypervisor_cpu_ready_time_ppm' => :'Integer',
        :'hypervisor_cpu_usage_ppm' => :'Integer',
        :'hypervisor_io_bandwidth_kbps' => :'Integer',
        :'hypervisor_memory_usage_ppm' => :'Integer',
        :'hypervisor_num_io' => :'Integer',
        :'hypervisor_num_iops' => :'Integer',
        :'hypervisor_num_read_io' => :'Integer',
        :'hypervisor_num_read_iops' => :'Integer',
        :'hypervisor_num_received_bytes' => :'Integer',
        :'hypervisor_num_transmitted_bytes' => :'Integer',
        :'hypervisor_num_write_io' => :'Integer',
        :'hypervisor_num_write_iops' => :'Integer',
        :'hypervisor_read_io_bandwidth_kbps' => :'Integer',
        :'hypervisor_swap_in_rate_kbps' => :'Integer',
        :'hypervisor_swap_out_rate_kbps' => :'Integer',
        :'hypervisor_timespan_micros' => :'Integer',
        :'hypervisor_total_io_size_kb' => :'Integer',
        :'hypervisor_total_io_time_micros' => :'Integer',
        :'hypervisor_total_read_io_size_kb' => :'Integer',
        :'hypervisor_write_io_bandwidth_kbps' => :'Integer',
        :'hypervisor_type' => :'String',
        :'memory_usage_ppm' => :'Integer',
        :'timestamp' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixVmm::VmmV40EsxiStatsVmStatsTuple` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixVmm::VmmV40EsxiStatsVmStatsTuple`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'check_score')
        self.check_score = attributes[:'check_score']
      end

      if attributes.key?(:'cluster')
        self.cluster = attributes[:'cluster']
      end

      if attributes.key?(:'controller_avg_io_latency_micros')
        self.controller_avg_io_latency_micros = attributes[:'controller_avg_io_latency_micros']
      end

      if attributes.key?(:'controller_avg_read_io_latency_micros')
        self.controller_avg_read_io_latency_micros = attributes[:'controller_avg_read_io_latency_micros']
      end

      if attributes.key?(:'controller_avg_read_io_size_kb')
        self.controller_avg_read_io_size_kb = attributes[:'controller_avg_read_io_size_kb']
      end

      if attributes.key?(:'controller_avg_write_io_latency_micros')
        self.controller_avg_write_io_latency_micros = attributes[:'controller_avg_write_io_latency_micros']
      end

      if attributes.key?(:'controller_avg_write_io_size_kb')
        self.controller_avg_write_io_size_kb = attributes[:'controller_avg_write_io_size_kb']
      end

      if attributes.key?(:'controller_io_bandwidth_kbps')
        self.controller_io_bandwidth_kbps = attributes[:'controller_io_bandwidth_kbps']
      end

      if attributes.key?(:'controller_num_io')
        self.controller_num_io = attributes[:'controller_num_io']
      end

      if attributes.key?(:'controller_num_iops')
        self.controller_num_iops = attributes[:'controller_num_iops']
      end

      if attributes.key?(:'controller_num_random_io')
        self.controller_num_random_io = attributes[:'controller_num_random_io']
      end

      if attributes.key?(:'controller_num_read_io')
        self.controller_num_read_io = attributes[:'controller_num_read_io']
      end

      if attributes.key?(:'controller_num_read_iops')
        self.controller_num_read_iops = attributes[:'controller_num_read_iops']
      end

      if attributes.key?(:'controller_num_seq_io')
        self.controller_num_seq_io = attributes[:'controller_num_seq_io']
      end

      if attributes.key?(:'controller_num_write_io')
        self.controller_num_write_io = attributes[:'controller_num_write_io']
      end

      if attributes.key?(:'controller_num_write_iops')
        self.controller_num_write_iops = attributes[:'controller_num_write_iops']
      end

      if attributes.key?(:'controller_random_io_ppm')
        self.controller_random_io_ppm = attributes[:'controller_random_io_ppm']
      end

      if attributes.key?(:'controller_read_io_bandwidth_kbps')
        self.controller_read_io_bandwidth_kbps = attributes[:'controller_read_io_bandwidth_kbps']
      end

      if attributes.key?(:'controller_read_io_ppm')
        self.controller_read_io_ppm = attributes[:'controller_read_io_ppm']
      end

      if attributes.key?(:'controller_seq_io_ppm')
        self.controller_seq_io_ppm = attributes[:'controller_seq_io_ppm']
      end

      if attributes.key?(:'controller_storage_tier_ssd_usage_bytes')
        self.controller_storage_tier_ssd_usage_bytes = attributes[:'controller_storage_tier_ssd_usage_bytes']
      end

      if attributes.key?(:'controller_timespan_micros')
        self.controller_timespan_micros = attributes[:'controller_timespan_micros']
      end

      if attributes.key?(:'controller_total_io_size_kb')
        self.controller_total_io_size_kb = attributes[:'controller_total_io_size_kb']
      end

      if attributes.key?(:'controller_total_io_time_micros')
        self.controller_total_io_time_micros = attributes[:'controller_total_io_time_micros']
      end

      if attributes.key?(:'controller_total_read_io_size_kb')
        self.controller_total_read_io_size_kb = attributes[:'controller_total_read_io_size_kb']
      end

      if attributes.key?(:'controller_total_read_io_time_micros')
        self.controller_total_read_io_time_micros = attributes[:'controller_total_read_io_time_micros']
      end

      if attributes.key?(:'controller_total_transformed_usage_bytes')
        self.controller_total_transformed_usage_bytes = attributes[:'controller_total_transformed_usage_bytes']
      end

      if attributes.key?(:'controller_user_bytes')
        self.controller_user_bytes = attributes[:'controller_user_bytes']
      end

      if attributes.key?(:'controller_write_io_bandwidth_kbps')
        self.controller_write_io_bandwidth_kbps = attributes[:'controller_write_io_bandwidth_kbps']
      end

      if attributes.key?(:'controller_write_io_ppm')
        self.controller_write_io_ppm = attributes[:'controller_write_io_ppm']
      end

      if attributes.key?(:'hypervisor_avg_io_latency_micros')
        self.hypervisor_avg_io_latency_micros = attributes[:'hypervisor_avg_io_latency_micros']
      end

      if attributes.key?(:'hypervisor_cpu_ready_time_ppm')
        self.hypervisor_cpu_ready_time_ppm = attributes[:'hypervisor_cpu_ready_time_ppm']
      end

      if attributes.key?(:'hypervisor_cpu_usage_ppm')
        self.hypervisor_cpu_usage_ppm = attributes[:'hypervisor_cpu_usage_ppm']
      end

      if attributes.key?(:'hypervisor_io_bandwidth_kbps')
        self.hypervisor_io_bandwidth_kbps = attributes[:'hypervisor_io_bandwidth_kbps']
      end

      if attributes.key?(:'hypervisor_memory_usage_ppm')
        self.hypervisor_memory_usage_ppm = attributes[:'hypervisor_memory_usage_ppm']
      end

      if attributes.key?(:'hypervisor_num_io')
        self.hypervisor_num_io = attributes[:'hypervisor_num_io']
      end

      if attributes.key?(:'hypervisor_num_iops')
        self.hypervisor_num_iops = attributes[:'hypervisor_num_iops']
      end

      if attributes.key?(:'hypervisor_num_read_io')
        self.hypervisor_num_read_io = attributes[:'hypervisor_num_read_io']
      end

      if attributes.key?(:'hypervisor_num_read_iops')
        self.hypervisor_num_read_iops = attributes[:'hypervisor_num_read_iops']
      end

      if attributes.key?(:'hypervisor_num_received_bytes')
        self.hypervisor_num_received_bytes = attributes[:'hypervisor_num_received_bytes']
      end

      if attributes.key?(:'hypervisor_num_transmitted_bytes')
        self.hypervisor_num_transmitted_bytes = attributes[:'hypervisor_num_transmitted_bytes']
      end

      if attributes.key?(:'hypervisor_num_write_io')
        self.hypervisor_num_write_io = attributes[:'hypervisor_num_write_io']
      end

      if attributes.key?(:'hypervisor_num_write_iops')
        self.hypervisor_num_write_iops = attributes[:'hypervisor_num_write_iops']
      end

      if attributes.key?(:'hypervisor_read_io_bandwidth_kbps')
        self.hypervisor_read_io_bandwidth_kbps = attributes[:'hypervisor_read_io_bandwidth_kbps']
      end

      if attributes.key?(:'hypervisor_swap_in_rate_kbps')
        self.hypervisor_swap_in_rate_kbps = attributes[:'hypervisor_swap_in_rate_kbps']
      end

      if attributes.key?(:'hypervisor_swap_out_rate_kbps')
        self.hypervisor_swap_out_rate_kbps = attributes[:'hypervisor_swap_out_rate_kbps']
      end

      if attributes.key?(:'hypervisor_timespan_micros')
        self.hypervisor_timespan_micros = attributes[:'hypervisor_timespan_micros']
      end

      if attributes.key?(:'hypervisor_total_io_size_kb')
        self.hypervisor_total_io_size_kb = attributes[:'hypervisor_total_io_size_kb']
      end

      if attributes.key?(:'hypervisor_total_io_time_micros')
        self.hypervisor_total_io_time_micros = attributes[:'hypervisor_total_io_time_micros']
      end

      if attributes.key?(:'hypervisor_total_read_io_size_kb')
        self.hypervisor_total_read_io_size_kb = attributes[:'hypervisor_total_read_io_size_kb']
      end

      if attributes.key?(:'hypervisor_write_io_bandwidth_kbps')
        self.hypervisor_write_io_bandwidth_kbps = attributes[:'hypervisor_write_io_bandwidth_kbps']
      end

      if attributes.key?(:'hypervisor_type')
        self.hypervisor_type = attributes[:'hypervisor_type']
      end

      if attributes.key?(:'memory_usage_ppm')
        self.memory_usage_ppm = attributes[:'memory_usage_ppm']
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          check_score == o.check_score &&
          cluster == o.cluster &&
          controller_avg_io_latency_micros == o.controller_avg_io_latency_micros &&
          controller_avg_read_io_latency_micros == o.controller_avg_read_io_latency_micros &&
          controller_avg_read_io_size_kb == o.controller_avg_read_io_size_kb &&
          controller_avg_write_io_latency_micros == o.controller_avg_write_io_latency_micros &&
          controller_avg_write_io_size_kb == o.controller_avg_write_io_size_kb &&
          controller_io_bandwidth_kbps == o.controller_io_bandwidth_kbps &&
          controller_num_io == o.controller_num_io &&
          controller_num_iops == o.controller_num_iops &&
          controller_num_random_io == o.controller_num_random_io &&
          controller_num_read_io == o.controller_num_read_io &&
          controller_num_read_iops == o.controller_num_read_iops &&
          controller_num_seq_io == o.controller_num_seq_io &&
          controller_num_write_io == o.controller_num_write_io &&
          controller_num_write_iops == o.controller_num_write_iops &&
          controller_random_io_ppm == o.controller_random_io_ppm &&
          controller_read_io_bandwidth_kbps == o.controller_read_io_bandwidth_kbps &&
          controller_read_io_ppm == o.controller_read_io_ppm &&
          controller_seq_io_ppm == o.controller_seq_io_ppm &&
          controller_storage_tier_ssd_usage_bytes == o.controller_storage_tier_ssd_usage_bytes &&
          controller_timespan_micros == o.controller_timespan_micros &&
          controller_total_io_size_kb == o.controller_total_io_size_kb &&
          controller_total_io_time_micros == o.controller_total_io_time_micros &&
          controller_total_read_io_size_kb == o.controller_total_read_io_size_kb &&
          controller_total_read_io_time_micros == o.controller_total_read_io_time_micros &&
          controller_total_transformed_usage_bytes == o.controller_total_transformed_usage_bytes &&
          controller_user_bytes == o.controller_user_bytes &&
          controller_write_io_bandwidth_kbps == o.controller_write_io_bandwidth_kbps &&
          controller_write_io_ppm == o.controller_write_io_ppm &&
          hypervisor_avg_io_latency_micros == o.hypervisor_avg_io_latency_micros &&
          hypervisor_cpu_ready_time_ppm == o.hypervisor_cpu_ready_time_ppm &&
          hypervisor_cpu_usage_ppm == o.hypervisor_cpu_usage_ppm &&
          hypervisor_io_bandwidth_kbps == o.hypervisor_io_bandwidth_kbps &&
          hypervisor_memory_usage_ppm == o.hypervisor_memory_usage_ppm &&
          hypervisor_num_io == o.hypervisor_num_io &&
          hypervisor_num_iops == o.hypervisor_num_iops &&
          hypervisor_num_read_io == o.hypervisor_num_read_io &&
          hypervisor_num_read_iops == o.hypervisor_num_read_iops &&
          hypervisor_num_received_bytes == o.hypervisor_num_received_bytes &&
          hypervisor_num_transmitted_bytes == o.hypervisor_num_transmitted_bytes &&
          hypervisor_num_write_io == o.hypervisor_num_write_io &&
          hypervisor_num_write_iops == o.hypervisor_num_write_iops &&
          hypervisor_read_io_bandwidth_kbps == o.hypervisor_read_io_bandwidth_kbps &&
          hypervisor_swap_in_rate_kbps == o.hypervisor_swap_in_rate_kbps &&
          hypervisor_swap_out_rate_kbps == o.hypervisor_swap_out_rate_kbps &&
          hypervisor_timespan_micros == o.hypervisor_timespan_micros &&
          hypervisor_total_io_size_kb == o.hypervisor_total_io_size_kb &&
          hypervisor_total_io_time_micros == o.hypervisor_total_io_time_micros &&
          hypervisor_total_read_io_size_kb == o.hypervisor_total_read_io_size_kb &&
          hypervisor_write_io_bandwidth_kbps == o.hypervisor_write_io_bandwidth_kbps &&
          hypervisor_type == o.hypervisor_type &&
          memory_usage_ppm == o.memory_usage_ppm &&
          timestamp == o.timestamp
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [check_score, cluster, controller_avg_io_latency_micros, controller_avg_read_io_latency_micros, controller_avg_read_io_size_kb, controller_avg_write_io_latency_micros, controller_avg_write_io_size_kb, controller_io_bandwidth_kbps, controller_num_io, controller_num_iops, controller_num_random_io, controller_num_read_io, controller_num_read_iops, controller_num_seq_io, controller_num_write_io, controller_num_write_iops, controller_random_io_ppm, controller_read_io_bandwidth_kbps, controller_read_io_ppm, controller_seq_io_ppm, controller_storage_tier_ssd_usage_bytes, controller_timespan_micros, controller_total_io_size_kb, controller_total_io_time_micros, controller_total_read_io_size_kb, controller_total_read_io_time_micros, controller_total_transformed_usage_bytes, controller_user_bytes, controller_write_io_bandwidth_kbps, controller_write_io_ppm, hypervisor_avg_io_latency_micros, hypervisor_cpu_ready_time_ppm, hypervisor_cpu_usage_ppm, hypervisor_io_bandwidth_kbps, hypervisor_memory_usage_ppm, hypervisor_num_io, hypervisor_num_iops, hypervisor_num_read_io, hypervisor_num_read_iops, hypervisor_num_received_bytes, hypervisor_num_transmitted_bytes, hypervisor_num_write_io, hypervisor_num_write_iops, hypervisor_read_io_bandwidth_kbps, hypervisor_swap_in_rate_kbps, hypervisor_swap_out_rate_kbps, hypervisor_timespan_micros, hypervisor_total_io_size_kb, hypervisor_total_io_time_micros, hypervisor_total_read_io_size_kb, hypervisor_write_io_bandwidth_kbps, hypervisor_type, memory_usage_ppm, timestamp].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
