=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module NutanixVmm
  # Storage provided by Nutanix ADSF.
  class VmmV40EsxiConfigVmDisk < ApiModelBase
    # Size of the disk in bytes.
    attr_accessor :disk_size_bytes

    attr_accessor :storage_container

    attr_accessor :storage_config

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'disk_size_bytes' => :'diskSizeBytes',
        :'storage_container' => :'storageContainer',
        :'storage_config' => :'storageConfig'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'disk_size_bytes' => :'Integer',
        :'storage_container' => :'VmmV40EsxiConfigVmDiskContainerReference',
        :'storage_config' => :'VmmV40EsxiConfigVmDiskStorageConfig'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixVmm::VmmV40EsxiConfigVmDisk` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixVmm::VmmV40EsxiConfigVmDisk`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'disk_size_bytes')
        self.disk_size_bytes = attributes[:'disk_size_bytes']
      end

      if attributes.key?(:'storage_container')
        self.storage_container = attributes[:'storage_container']
      end

      if attributes.key?(:'storage_config')
        self.storage_config = attributes[:'storage_config']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@disk_size_bytes.nil? && @disk_size_bytes < 1
        invalid_properties.push('invalid value for "disk_size_bytes", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@disk_size_bytes.nil? && @disk_size_bytes < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] disk_size_bytes Value to be assigned
    def disk_size_bytes=(disk_size_bytes)
      if disk_size_bytes.nil?
        fail ArgumentError, 'disk_size_bytes cannot be nil'
      end

      if disk_size_bytes < 1
        fail ArgumentError, 'invalid value for "disk_size_bytes", must be greater than or equal to 1.'
      end

      @disk_size_bytes = disk_size_bytes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          disk_size_bytes == o.disk_size_bytes &&
          storage_container == o.storage_container &&
          storage_config == o.storage_config
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [disk_size_bytes, storage_container, storage_config].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
