=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module NutanixVmm
  # The references to Prism Element cluster and respective retained images.
  class VmmV40ContentImageImportConfig < ApiModelBase
    # Cluster external identifier.
    attr_accessor :cluster_ext_id

    # List of external identifiers for images that need to be imported.
    attr_accessor :images_ext_ids

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cluster_ext_id' => :'clusterExtId',
        :'images_ext_ids' => :'imagesExtIds'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cluster_ext_id' => :'String',
        :'images_ext_ids' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixVmm::VmmV40ContentImageImportConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixVmm::VmmV40ContentImageImportConfig`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cluster_ext_id')
        self.cluster_ext_id = attributes[:'cluster_ext_id']
      else
        self.cluster_ext_id = nil
      end

      if attributes.key?(:'images_ext_ids')
        if (value = attributes[:'images_ext_ids']).is_a?(Array)
          self.images_ext_ids = value
        end
      else
        self.images_ext_ids = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @cluster_ext_id.nil?
        invalid_properties.push('invalid value for "cluster_ext_id", cluster_ext_id cannot be nil.')
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if @cluster_ext_id !~ pattern
        invalid_properties.push("invalid value for \"cluster_ext_id\", must conform to the pattern #{pattern}.")
      end

      if @images_ext_ids.nil?
        invalid_properties.push('invalid value for "images_ext_ids", images_ext_ids cannot be nil.')
      end

      if @images_ext_ids.length > 100
        invalid_properties.push('invalid value for "images_ext_ids", number of items must be less than or equal to 100.')
      end

      if @images_ext_ids.length < 0
        invalid_properties.push('invalid value for "images_ext_ids", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @cluster_ext_id.nil?
      return false if @cluster_ext_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if @images_ext_ids.nil?
      return false if @images_ext_ids.length > 100
      return false if @images_ext_ids.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] cluster_ext_id Value to be assigned
    def cluster_ext_id=(cluster_ext_id)
      if cluster_ext_id.nil?
        fail ArgumentError, 'cluster_ext_id cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if cluster_ext_id !~ pattern
        fail ArgumentError, "invalid value for \"cluster_ext_id\", must conform to the pattern #{pattern}."
      end

      @cluster_ext_id = cluster_ext_id
    end

    # Custom attribute writer method with validation
    # @param [Object] images_ext_ids Value to be assigned
    def images_ext_ids=(images_ext_ids)
      if images_ext_ids.nil?
        fail ArgumentError, 'images_ext_ids cannot be nil'
      end

      if images_ext_ids.length > 100
        fail ArgumentError, 'invalid value for "images_ext_ids", number of items must be less than or equal to 100.'
      end

      if images_ext_ids.length < 0
        fail ArgumentError, 'invalid value for "images_ext_ids", number of items must be greater than or equal to 0.'
      end

      @images_ext_ids = images_ext_ids
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cluster_ext_id == o.cluster_ext_id &&
          images_ext_ids == o.images_ext_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cluster_ext_id, images_ext_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
