=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.16.0

=end

require 'date'
require 'time'

module NutanixVmm
  class VmmV40AhvConfigMigrateNicType
    ASSIGN_IP = "ASSIGN_IP".freeze
    RELEASE_IP = "RELEASE_IP".freeze
    _UNKNOWN = "$UNKNOWN".freeze
    _REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [ASSIGN_IP, RELEASE_IP, _UNKNOWN, _REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if VmmV40AhvConfigMigrateNicType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #VmmV40AhvConfigMigrateNicType"
    end
  end
end
