=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NutanixVmm::VmApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VmApi' do
  before do
    # run before each test
    @api_instance = NutanixVmm::VmApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VmApi' do
    it 'should create an instance of VmApi' do
      expect(@api_instance).to be_instance_of(NutanixVmm::VmApi)
    end
  end

  # unit tests for assign_ip_by_id
  # Assign an IP address to the provided network device
  # Assigns a specific IP address to a network device attached to a managed network.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM NIC of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_assign_ip_params 
  # @param [Hash] opts the optional parameters
  # @return [AssignIpById202Response]
  describe 'assign_ip_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for assign_vm_owner
  # Assign owner of a VM
  # Assign the owner of a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_ownership_info 
  # @param [Hash] opts the optional parameters
  # @return [AssignVmOwner202Response1]
  describe 'assign_vm_owner test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for associate_categories
  # Associate categories to a VM
  # Associate categories to a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_associate_vm_categories_params 
  # @param [Hash] opts the optional parameters
  # @return [AssociateCategories202Response1]
  describe 'associate_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for clone_vm
  # Clone a VM
  # Clones an existing virtual machine. This operation also includes updating the existing configuration during the clone operation.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @option opts [VmmV40AhvConfigCloneOverrideParams] :vmm_v40_ahv_config_clone_override_params 
  # @return [CloneVm202Response]
  describe 'clone_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_cd_rom
  # Create a CD-ROM device for a VM
  # Creates and attaches a CD-ROM device to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_cd_rom 
  # @param [Hash] opts the optional parameters
  # @return [CreateCdRom202Response]
  describe 'create_cd_rom test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_disk
  # Create a disk device for a VM
  # Creates and attaches a disk device to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_disk 
  # @param [Hash] opts the optional parameters
  # @return [CreateDisk202Response]
  describe 'create_disk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_gpu
  # Attach a GPU device to a VM
  # Attaches a GPU device to a virtual machine
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_gpu 
  # @param [Hash] opts the optional parameters
  # @return [CreateGpu202Response]
  describe 'create_gpu test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_nic
  # Create a network device for a VM
  # Creates and attaches a network device to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_nic 
  # @param [Hash] opts the optional parameters
  # @return [CreateNic202Response]
  describe 'create_nic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_pcie_device
  # Create a PCIe device for a VM
  # Creates and attaches a PCIe device to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_pcie_device 
  # @param [Hash] opts the optional parameters
  # @return [CreatePcieDevice202Response]
  describe 'create_pcie_device test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_serial_port
  # Create a serial port for a VM
  # Creates and attaches a serial port device to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_serial_port 
  # @param [Hash] opts the optional parameters
  # @return [CreateSerialPort202Response]
  describe 'create_serial_port test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_vm
  # Create a VM
  # Creates a Virtual Machine with the provided configuration.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_vm 
  # @param [Hash] opts the optional parameters
  # @return [CreateVm202Response]
  describe 'create_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cross_cluster_migrate_vm
  # Migrate a VM across clusters
  # Migrates a VM from the current cluster to a new target cluster. Supports the dry-run option, which if used results only in validation of the cross-cluster migration parameters and pre-requisites.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_vm_cross_cluster_migrate_params Input on how to migrate a VM across clusters.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :dryrun A URL query parameter that allows long running operations to execute in a dry-run mode providing ability to identify trouble spots and system failures without performing the actual operation. Additionally this mode also offers a summary snapshot of the resultant system in order to better understand how things fit together. The operation runs in dry-run mode only if the provided value is true. 
  # @return [CrossClusterMigrateVm202Response]
  describe 'cross_cluster_migrate_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for customize_guest_vm
  # Stage guest customization configuration details
  # Stage a Sysprep or cloud-init configuration file to be used by the guest for the next boot. Note that the Sysprep command must be used to generalize the Windows VMs before triggering this API call.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_guest_customization_params 
  # @param [Hash] opts the optional parameters
  # @return [CustomizeGuestVm202Response]
  describe 'customize_guest_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_cd_rom_by_id
  # Remove a CD-ROM device from a VM
  # Removes the specified CD-ROM device from a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a CD-ROM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeleteCdRomById202Response]
  describe 'delete_cd_rom_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_disk_by_id
  # Removes the specified disk device from a virtual machine.
  # Removes the specified disk device from a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM disk of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeleteDiskById202Response]
  describe 'delete_disk_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_gpu_by_id
  # Remove a GPU device from a VM
  # Removes the specified GPU device from a virtual machine
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM GPU of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeleteGpuById202Response]
  describe 'delete_gpu_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_nic_by_id
  # Remove a network device from a VM
  # Removes the specified network device from a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM NIC of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeleteNicById202Response]
  describe 'delete_nic_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_pcie_device_by_id
  # Remove a PCIe device from a VM
  # Removes the specified PCIe device from a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id Globally unique identifier of a PCIe device  of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeletePcieDeviceById202Response]
  describe 'delete_pcie_device_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_serial_port_by_id
  # Remove a serial port from a VM
  # Removes the specified serial port from a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id The globally unique identifier of a serial port of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeleteSerialPortById202Response]
  describe 'delete_serial_port_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_vm_by_id
  # Delete a VM
  # Delete the specified virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeleteVmById202Response]
  describe 'delete_vm_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disassociate_categories
  # Disassociate categories from a VM
  # Disassociate categories from a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_disassociate_vm_categories_params 
  # @param [Hash] opts the optional parameters
  # @return [DisassociateCategories202Response1]
  describe 'disassociate_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for eject_cd_rom_by_id
  # Ejects an ISO from the provided CD-ROM device
  # Ejects the ISO currently inserted into a CD-ROM device on a Virtual Machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a CD-ROM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [EjectCdRomById202Response]
  describe 'eject_cd_rom_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_cd_rom_by_id
  # Get configuration details for the provided CD-ROM
  # Retrieves configuration details for the provided CD-ROM device attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a CD-ROM of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetCdRomById200Response]
  describe 'get_cd_rom_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_disk_by_id
  # Get configuration details for the provided disk device
  # Retrieves configuration details for the provided disk device attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM disk of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetDiskById200Response]
  describe 'get_disk_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_gpu_by_id
  # Get configuration details for the provided GPU device
  # Retrieves configuration details for the provided GPU device attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM GPU of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetGpuById200Response]
  describe 'get_gpu_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_guest_tools_by_id
  # Get VM NGT configuration
  # Retrieves the Nutanix Guest Tools configuration for a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetGuestToolsById200Response]
  describe 'get_guest_tools_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_nic_by_id
  # Get configuration details for the provided network device
  # Retrieves configuration details for the provided network device attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM NIC of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetNicById200Response]
  describe 'get_nic_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pcie_device_by_id
  # Get configuration details for the provided PCIe device
  # Retrieves configuration details for the provided PCIe device attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id Globally unique identifier of a PCIe device  of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetPcieDeviceById200Response]
  describe 'get_pcie_device_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_serial_port_by_id
  # Get configuration details for the provided serial port
  # Retrieves configuration details for the provided serial port attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id The globally unique identifier of a serial port of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetSerialPortById200Response]
  describe 'get_serial_port_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_vm_by_id
  # Get VM configuration details
  # Retrieves configuration details for a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @return [GetVmById200Response1]
  describe 'get_vm_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for insert_cd_rom_by_id
  # Inserts an ISO in the provided CD-ROM device
  # Inserts the defined ISO into a CD-ROM device attached to a Virtual Machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a CD-ROM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_cd_rom_insert_params 
  # @param [Hash] opts the optional parameters
  # @return [InsertCdRomById202Response]
  describe 'insert_cd_rom_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for insert_vm_guest_tools
  # Insert NGT ISO into an available CD-ROM for a VM
  # Inserts the Nutanix Guest Tools installation and configuration ISO into a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_guest_tools_insert_config 
  # @param [Hash] opts the optional parameters
  # @return [InsertVmGuestTools202Response]
  describe 'insert_vm_guest_tools test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for install_vm_guest_tools
  # Install NGT in a VM
  # Installs Nutanix Guest Tools in a Virtual Machine by using the provided credentials.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_guest_tools_install_config 
  # @param [Hash] opts the optional parameters
  # @return [InstallVmGuestTools202Response]
  describe 'install_vm_guest_tools test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_cd_roms_by_vm_id
  # List CD-ROMs attached to a VM
  # Lists the CD-ROM devices attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @return [ListCdRomsByVmId200Response]
  describe 'list_cd_roms_by_vm_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_disks_by_vm_id
  # List disks attached to a VM
  # Lists the disk devices attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @return [ListDisksByVmId200Response]
  describe 'list_disks_by_vm_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_gpus_by_vm_id
  # List GPUs attached to a VM
  # Lists the GPU devices attached to a virtual machine
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @option opts [String] :filter A URL query parameter that allows clients to filter a collection of resources. The expression specified with $filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the $filter must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. For example, filter &#39;$filter&#x3D;name eq &#39;karbon-ntnx-1.0&#39; would filter the result on cluster name &#39;karbon-ntnx1.0&#39;, filter &#39;$filter&#x3D;startswith(name, &#39;C&#39;)&#39; would filter on cluster name starting with &#39;C&#39;. The filter can be applied to the following fields: - mode - vendor 
  # @return [ListGpusByVmId200Response]
  describe 'list_gpus_by_vm_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_nics_by_vm_id
  # List network devices attached to a VM
  # Lists the network devices attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @option opts [String] :filter A URL query parameter that allows clients to filter a collection of resources. The expression specified with $filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the $filter must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. For example, filter &#39;$filter&#x3D;name eq &#39;karbon-ntnx-1.0&#39; would filter the result on cluster name &#39;karbon-ntnx1.0&#39;, filter &#39;$filter&#x3D;startswith(name, &#39;C&#39;)&#39; would filter on cluster name starting with &#39;C&#39;. The filter can be applied to the following fields: - networkInfo/subnet/extId 
  # @return [ListNicsByVmId200Response]
  describe 'list_nics_by_vm_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pcie_devices_by_vm_id
  # List PCIe devices attached to a VM
  # Lists all the PCIe devices attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @return [ListPcieDevicesByVmId200Response]
  describe 'list_pcie_devices_by_vm_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_serial_ports_by_vm_id
  # List serial ports attached to a VM
  # Lists the serial ports attached to a virtual machine.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @return [ListSerialPortsByVmId200Response]
  describe 'list_serial_ports_by_vm_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_vms
  # List VMs
  # Lists the Virtual Machines defined on the system. List of Virtual Machines can be further filtered out using various filtering options.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @option opts [String] :filter A URL query parameter that allows clients to filter a collection of resources. The expression specified with $filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the $filter must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. For example, filter &#39;$filter&#x3D;name eq &#39;karbon-ntnx-1.0&#39; would filter the result on cluster name &#39;karbon-ntnx1.0&#39;, filter &#39;$filter&#x3D;startswith(name, &#39;C&#39;)&#39; would filter on cluster name starting with &#39;C&#39;. The filter can be applied to the following fields: - apcConfig/cpuModel/extId - apcConfig/cpuModel/name - apcConfig/isApcEnabled - cluster/extId - extId - gpus - hardwareClockTimezone - host/extId - isAgentVm - isCpuHotplugEnabled - isCpuPassthroughEnabled - isGpuConsoleEnabled - isLiveMigrateCapable - isMemoryOvercommitEnabled - isScsiControllerEnabled - isVcpuHardPinningEnabled - isVgaConsoleEnabled - machineType - memorySizeBytes - name - nics - numCoresPerSocket - numNumaNodes - numSockets - numThreadsPerCore - powerState 
  # @option opts [String] :orderby A URL query parameter that allows clients to specify the sort criteria for the returned list of objects. Resources can be sorted in ascending order using asc or descending order using desc. If asc or desc are not specified, the resources will be sorted in ascending order by default. For example, &#39;$orderby&#x3D;templateName desc&#39; would get all templates sorted by templateName in descending order. The orderby can be applied to the following fields: - memorySizeBytes - name - numCoresPerSocket - numNumaNodes - numSockets - numThreadsPerCore 
  # @option opts [String] :select A URL query parameter that allows clients to request a specific set of properties for each entity or complex type. Expression specified with the $select must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. If a $select expression consists of a single select item that is an asterisk (i.e., *), then all properties on the matching resource will be returned. - apcConfig/cpuModel/extId - apcConfig/cpuModel/name - apcConfig/isApcEnabled - availabilityZone - biosUuid - bootConfig - categories - cdRoms - cluster/extId - createTime - description - disks - enabledCpuFeatures - extId - generationUuid - gpus - guestCustomization - guestTools - hardwareClockTimezone - host/extId - isAgentVm - isBrandingEnabled - isCpuHotplugEnabled - isCpuPassthroughEnabled - isCrossClusterMigrationInProgress - isGpuConsoleEnabled - isLiveMigrateCapable - isMemoryOvercommitEnabled - isScsiControllerEnabled - isVcpuHardPinningEnabled - isVgaConsoleEnabled - links - machineType - memorySizeBytes - name - nics - numCoresPerSocket - numNumaNodes - numSockets - numThreadsPerCore - ownershipInfo - pcieDevices - powerState - protectionPolicyState - protectionType - serialPorts - source - storageConfig - tenantId - updateTime - vtpmConfig 
  # @return [ListVms200Response1]
  describe 'list_vms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for migrate_nic_by_id
  # Migrate a network device to another subnet
  # Migrates a network device attached to a Virtual Machine to another subnet. This can be used to move network devices between VLAN and VPC subnets.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM NIC of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_migrate_nic_config 
  # @param [Hash] opts the optional parameters
  # @return [MigrateNicById202Response]
  describe 'migrate_nic_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for migrate_vm_disks
  # VmDisk migration between storage containers
  # Specifies the VmDisks of a VM for migration and the migration plan for them. If all the disks of a VM need to be migrated to the same storage container, only a single migration plan with only the external ID of the destination storage container is needed.  If the disks are being migrated to different containers, one plan per disk needs to be specified.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_disk_migration_params 
  # @param [Hash] opts the optional parameters
  # @return [MigrateVmDisks202Response]
  describe 'migrate_vm_disks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for migrate_vm_to_host
  # Host to host VM migration
  # Migrate a VM to another host within the same cluster.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_vm_migrate_to_host_params The request body for migrating a VM from one host to another within a cluster.
  # @param [Hash] opts the optional parameters
  # @return [MigrateVmToHost202Response]
  describe 'migrate_vm_to_host test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for power_cycle_vm
  # Force a power cycle for a VM
  # Force a power-cycle for a virtual machine. This operation is equivalent to requesting a VM power-off followed by the VM power-on. Power cycling a VM is slower than resetting it, but it will be creating a fresh instance of the virtual machine. When resetting, the same instance is restarted within the context of the running VM instance.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [PowerCycleVm202Response]
  describe 'power_cycle_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for power_off_vm
  # Force power off a VM
  # Forceably shuts down a virtual machine which is equivalent to removing the power cable. Note: The forced shutdown may result in data loss if any operations are in progress during the shutdown.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [PowerOffVm202Response1]
  describe 'power_off_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for power_on_vm
  # Turn on a VM
  # Turns a Virtual Machine on.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [PowerOnVm202Response1]
  describe 'power_on_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reboot_guest_vm
  # Restart the VM using NGT
  # Collaborative reboot of a Virtual Machine, requesting Nutanix Guest Tools to trigger a reboot from within the VM.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_guest_power_options 
  # @param [Hash] opts the optional parameters
  # @return [RebootVm202Response]
  describe 'reboot_guest_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reboot_vm
  # Reboot a VM using ACPI
  # Collaborative reboot of a Virtual Machine through the ACPI support in the operating system.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [RebootVm202Response]
  describe 'reboot_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for release_ip_by_id
  # Release an assigned IP address from the provided network device
  # Releases the IP address assignment from a network device attached to a managed network.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM NIC of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [ReleaseIpById202Response]
  describe 'release_ip_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reset_vm
  # Reset a VM immediately
  # Force reset of a Virtual Machine, without waiting for the guest VM to shutdown itself. Resetting a VM is faster than power-cycle as the reset occurs within the context of the running virtual machine instance rather than creating a fresh instance.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [ResetVm202Response1]
  describe 'reset_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revert_vm
  # Revert the AHV VM.
  # Revert VM identified by {extId}. This does an in-place VM restore from a specified VM Recovery Point.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_revert_params 
  # @param [Hash] opts the optional parameters
  # @return [RevertVm202Response1]
  describe 'revert_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for shutdown_guest_vm
  # Shutdown the VM using NGT
  # Collaborative shutdown of a Virtual Machine, requesting Nutanix Guest Tools to trigger a shutdown from within the VM.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_guest_power_options 
  # @param [Hash] opts the optional parameters
  # @return [ShutdownVm202Response]
  describe 'shutdown_guest_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for shutdown_vm
  # Shutdown the VM using ACPI
  # Collaborative shutdown of a Virtual Machine through the ACPI support in the operating system.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [ShutdownVm202Response]
  describe 'shutdown_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for uninstall_vm_guest_tools
  # Uninstall NGT from a VM
  # Trigger an in-guest uninstallation of Nutanix Guest Tools.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [UninstallVmGuestTools202Response]
  describe 'uninstall_vm_guest_tools test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_disk_by_id
  # Update the configuration for the provided disk device
  # Updates the configuration details for the provided disk device.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM disk of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided, the server will respond with  an HTTP-428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow the successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP-412 (Precondition Failed) response will be returned.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_disk 
  # @param [Hash] opts the optional parameters
  # @return [UpdateDiskById202Response]
  describe 'update_disk_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_guest_tools_by_id
  # Update NGT configuration for a VM
  # Updates the Nutanix Guest Tools configuration for a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided, the server will respond with  an HTTP-428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow the successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP-412 (Precondition Failed) response will be returned.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_guest_tools 
  # @param [Hash] opts the optional parameters
  # @return [UpdateGuestToolsById202Response]
  describe 'update_guest_tools_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_nic_by_id
  # Update the configuration for the provided network device
  # Updates the configuration details for the provided network device.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id A globally unique identifier of a VM NIC of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided, the server will respond with  an HTTP-428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow the successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP-412 (Precondition Failed) response will be returned.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_nic 
  # @param [Hash] opts the optional parameters
  # @return [UpdateNicById202Response]
  describe 'update_nic_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_serial_port_by_id
  # Update the configuration for the provided serial port
  # Updates the configuration details for the provided serial port.
  # @param vm_ext_id A globally unique identifier of a VM of type UUID.
  # @param ext_id The globally unique identifier of a serial port of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided, the server will respond with  an HTTP-428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow the successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP-412 (Precondition Failed) response will be returned.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_serial_port 
  # @param [Hash] opts the optional parameters
  # @return [UpdateSerialPortById202Response]
  describe 'update_serial_port_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_vm_by_id
  # Update configuration for a VM
  # Updates configuration details for a virtual machine.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided, the server will respond with  an HTTP-428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow the successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP-412 (Precondition Failed) response will be returned.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_vm 
  # @param [Hash] opts the optional parameters
  # @return [UpdateVmById202Response]
  describe 'update_vm_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upgrade_vm_guest_tools
  # Upgrade NGT inside a VM
  # Trigger an in-guest upgrade of Nutanix Guest Tools.
  # @param ext_id A globally unique identifier of a VM of type UUID.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param vmm_v40_ahv_config_guest_tools_upgrade_config 
  # @param [Hash] opts the optional parameters
  # @return [UpgradeVmGuestTools202Response]
  describe 'upgrade_vm_guest_tools test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
