=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVmm::AssignVmOwner202Response1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVmm::AssignVmOwner202Response1 do
  let(:instance) { NutanixVmm::AssignVmOwner202Response1.new }

  describe 'test an instance of AssignVmOwner202Response1' do
    it 'should create an instance of AssignVmOwner202Response1' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVmm::AssignVmOwner202Response1)
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
