=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVmm::IamV40AuthnUserStatusType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVmm::IamV40AuthnUserStatusType do
  #let(:instance) { NutanixVmm::IamV40AuthnUserStatusType.new }

  describe 'test an instance of IamV40AuthnUserStatusType' do
    it 'should create an instance of IamV40AuthnUserStatusType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVmm::IamV40AuthnUserStatusType)
    end
  end

end
