=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.16.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVmm::VmmV40AhvConfigGpuMode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVmm::VmmV40AhvConfigGpuMode do
  #let(:instance) { NutanixVmm::VmmV40AhvConfigGpuMode.new }

  describe 'test an instance of VmmV40AhvConfigGpuMode' do
    it 'should create an instance of VmmV40AhvConfigGpuMode' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVmm::VmmV40AhvConfigGpuMode)
    end
  end

end
