=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVmm::VmmV40AhvPoliciesConflictingVmAntiAffinityPolicy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVmm::VmmV40AhvPoliciesConflictingVmAntiAffinityPolicy do
  #let(:instance) { NutanixVmm::VmmV40AhvPoliciesConflictingVmAntiAffinityPolicy.new }

  describe 'test an instance of VmmV40AhvPoliciesConflictingVmAntiAffinityPolicy' do
    it 'should create an instance of VmmV40AhvPoliciesConflictingVmAntiAffinityPolicy' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVmm::VmmV40AhvPoliciesConflictingVmAntiAffinityPolicy)
    end
  end

  describe 'test attribute "conflicting_vm_anti_affinity_policy_ext_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
