=begin
#Nutanix Virtual Machine Management APIs

#Manage the life-cycle of virtual machines hosted on Nutanix

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVmm::VmmV40AhvConfigVmCrossClusterMigrateParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVmm::VmmV40AhvConfigVmCrossClusterMigrateParams do
  #let(:instance) { NutanixVmm::VmmV40AhvConfigVmCrossClusterMigrateParams.new }

  describe 'test an instance of VmmV40AhvConfigVmCrossClusterMigrateParams' do
    it 'should create an instance of VmmV40AhvConfigVmCrossClusterMigrateParams' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVmm::VmmV40AhvConfigVmCrossClusterMigrateParams)
    end
  end

  describe 'test attribute "target_availability_zone"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "target_cluster"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_live_migration"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "overrides"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
